version: '2'
services:
  mysql:
    image: mysql:8.0
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:23.2.1
    depends_on:
    - mysql
    environment:
    - DB_HOST_FILE=/run/secrets/bookstack_db_host
    - DB_DATABASE_FILE=/run/secrets/bookstack_db_database
    - DB_USERNAME_FILE=/run/secrets/bookstack_db_username
    - DB_PASSWORD_FILE=/run/secrets/bookstack_db_password
    #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
    - APP_URL=http://example.com
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"

volumes:
  mysql-data:
  uploads:
  storage-uploads:

secrets:
  bookstack_db_host:
    file: /path/to/secret/file1
  bookstack_db_database:
    file: /path/to/secret/file2
  bookstack_db_username:
    file: /path/to/secret/file3
  bookstack_db_password: 
    file: /path/to/secret/file4
